### ISSUE TITLE
Add ability to pass in a different dockerfile

### ISSUE THREAD

**Issue by ghop02** [devmasx/cached-docker-build-push#6]
Right now it looks like there is no configurable dockerfile.  This is a blocker if your dockerfile doesn't live at `./Dockerfile`

**Comment by MiguelSavignano** [comment]
@ghop02 
The latest version allows setting the Dockerfile path using `file` option.

Example:
```yaml
- uses: devmasx/cached-docker-build-push@v0.2.2
  with:
    image_name: devmasx/project-name-web
    image_tag: ${{ github.sha }}
    file: Dockerfile.web
    cache_stage_target: builder
    build_params: --build-arg=NPM_TOKEN=${{secrets.NPM_TOKEN}}
    push: true
```
